learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = "basic_app"
urlpatterns = [
    url(r"^relative/$",views.relative, name = "relative"),
    url(r"^basic_app/",views.other,name = "other"),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name = "index"),
    url(r"^basic_app/",include("basic_app.urls"))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text":"Hello world","number":100,"text1":"How are you"}
    return render(request, "basic_app/index.html", context_dict)

def other(request):
    return render(request, "basic_app/other.html")

def relative(request):
    return render(request, "basic_app/relative_url_templates.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <!-- <nav class="navbar navbar-default navbar-static-top">
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="#">Brand</a></li>
          <li><a class="navbar-link" href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Other</a></li>
        </ul>
      </div>
    </nav> -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="navbar-brand" href="{% url "index" %}">Brand</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "basic_app:other" %}">Other</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index!</h1>
    <h1>{{ text|upper }}</h1>
    <h1>{{ number|add:"100" }}</h1>
    <h1>{{ text1|cut:"you" }}</h1>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to other!</h1>
    <h2>This is inheritance</h2>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates!</h1>
    <a href="{% url "basic_app:other" %}">The other page</a>
    <a href="{% url "admin:index" %}">The admin page</a>
    <a href="{% url "index" %}">The index page</a>
  </body>
</html>